### ISSUE TITLE
Expand on README

### ISSUE THREAD

**Issue by ajlanghorn** [billinghamj/aws-google-login#1]
For newcomers, the README doesn't describe how this tool is used.

**Comment by LarsFronius** [comment]
A quick walkthrough on permissions on IAM would be very helpful, yes.

**Comment by billinghamj** [comment]
Oh hi, sorry - I didn't notice this issue!

We made this repo to make it easier for our devs to log into AWS using our Google Apps as an SSO provider.

I'll have a look at how it's set up and make a list of instructions. iirc, it requires some kind of setup on AWS in the IAM system.

**Comment by ajlanghorn** [comment]
It probably requires some sort of access through to STS and maybe Cognito.

**Comment by billinghamj** [comment]
Actually no - AWS keys aren't required, because the STS `assumeRoleWithWebIdentity` is authorized based on the token from Google Apps.

A Google OAuth app id/secret with a redirect url set up is required though. (https://imgur.com/ZyaXQP8)

And in AWS IAM, a "web identity provider" role must be set up with the audience being the Google app id (https://imgur.com/41SHviA)

The code in this repo:
1. gets an authorization code by redirecting the user through the Google OAuth flow
2. gets a JWT on the backend using that code and the secret key
3. checks the Google Apps domain (so other companies can't log into our AWS account)
4. creates temporary AWS credentials by assuming the IAM role using the JWT
5. redirects the user to the AWS login URL with the credentials in the parameters
6. https://imgur.com/Q0VHLah

The AWS credentials are very short lived (you are directed through the Heroku app again once they expire to generate new ones) and adopt the permissions you provide to the IAM role.

I'll convert this info into a more clear set of instructions soon, but for now this should provide the info required to make it work.
